#!/usr/bin/env python3
"""
Compare two tileconn.json files from the perspective of their consumer.

Two tileconn.json files (e.g. the one in prjxray-db and one generated by
rapidwright_tileconn.py) will generally NOT match entry-by-entry: any
spanning set of wire pairs reconstructs the same nodes, so the same device
can be encoded with different pair choices (short chains vs. long "direct"
pairs across tall tiles, etc.).

The meaningful equivalence test is the one the consumer performs
(prjxray.connections.Connections + prjxray.node_model.NodeModel):

1. Expand each file over the same tilegrid.json by pattern matching:
   for every tile instance whose type matches an entry, apply the entry's
   wire pairs to the tile at (grid_x + dx, grid_y + dy) if it exists and
   its type matches.
2. Merge the resulting concrete (tile, wire) pairs with union-find.
   Each disjoint set is one reconstructed node.
3. Compare the two node partitions.

The two files may also model different wire vocabularies (e.g. prjxray
drops wires listed in ignored_wires, while RapidWright enumerates every
wire).  A wire only one file knows about cannot affect the consumer of the
other file, so the partitions are compared *projected onto the common
wires*, and the vocabulary differences are reported separately.

Usage:
    python3 compare_tileconn.py \\
        --tilegrid   prjxray-db/artix7/xc7a50t/tilegrid.json \\
        --tileconn_a prjxray-db/artix7/xc7a50t/tileconn.json \\
        --tileconn_b tileconn_rapidwright.json

Exit status is 0 if the projected partitions are identical, 1 otherwise.
"""

import argparse
import json
from collections import defaultdict


class UnionFind():
    def __init__(self):
        self.parent = {}

    def find(self, x):
        parent = self.parent
        if x not in parent:
            parent[x] = x
            return x
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(self, a, b):
        root_a, root_b = self.find(a), self.find(b)
        if root_a != root_b:
            self.parent[root_a] = root_b


def build_partition(tileconn_path, grid):
    """ Expand a tileconn file over the grid and merge wires into nodes.

    Applies the same pattern-matching rule as
    prjxray.connections.Connections.all_possible_connections_from, then
    the same union-find merge as prjxray.node_model.NodeModel._build_nodes.

    Returns (nodes, wires) where nodes is a set of frozensets of
    (tile, wire) and wires is the set of all (tile, wire) mentioned by any
    applied connection.
    """
    coord_to_tile = {}
    for tile, info in grid.items():
        coord_to_tile[(info['grid_x'], info['grid_y'])] = (
            tile, info['type'])

    with open(tileconn_path) as f:
        tileconn = json.load(f)

    rules = defaultdict(list)
    for entry in tileconn:
        rules[entry['tile_types'][0]].append(
            (
                tuple(entry['grid_deltas']), entry['tile_types'][1],
                entry['wire_pairs']))

    uf = UnionFind()
    for (grid_x, grid_y), (tile1, tile_type1) in coord_to_tile.items():
        for (dx, dy), tile_type2, wire_pairs in rules.get(tile_type1, ()):
            target = coord_to_tile.get((grid_x + dx, grid_y + dy))
            if target is None or target[1] != tile_type2:
                continue

            tile2 = target[0]
            for wire1, wire2 in wire_pairs:
                uf.union((tile1, wire1), (tile2, wire2))

    groups = defaultdict(set)
    for wire in uf.parent:
        groups[uf.find(wire)].add(wire)

    nodes = set(frozenset(group) for group in groups.values())
    wires = set(uf.parent)
    return nodes, wires


def project(nodes, common_wires):
    """ Restrict a partition to a wire subset.

    Blocks that shrink below 2 wires carry no connectivity information and
    are dropped.
    """
    projected = set()
    for node in nodes:
        block = node & common_wires
        if len(block) >= 2:
            projected.add(frozenset(block))
    return projected


def describe_node(node, limit=4):
    wires = sorted(node)
    text = ', '.join('{}/{}'.format(tile, wire) for tile, wire in
                     wires[:limit])
    if len(wires) > limit:
        text += ', ... ({} wires total)'.format(len(wires))
    return '{' + text + '}'


def categorize_differences(diff_nodes, other_nodes):
    """ Explain how each differing node relates to the other partition. """
    wire_to_other = {}
    for node in other_nodes:
        for wire in node:
            wire_to_other[wire] = node

    categories = defaultdict(list)
    for node in diff_nodes:
        fragments = set()
        for wire in node:
            if wire in wire_to_other:
                fragments.add(wire_to_other[wire])

        if len(fragments) == 1:
            fragment = next(iter(fragments))
            if node < fragment:
                categories['merged into a larger node'].append(
                    (node, fragments))
                continue

        if all(fragment <= node for fragment in fragments):
            categories['split into smaller nodes'].append((node, fragments))
        else:
            categories['mismatched (crossed connections)'].append(
                (node, fragments))

    return categories


def report_differences(label, diff_nodes, other_nodes, max_examples):
    print('\nNodes only in {} ({}), by relation to the other file:'.format(
        label, len(diff_nodes)))
    categories = categorize_differences(diff_nodes, other_nodes)
    for category, examples in sorted(categories.items()):
        print('  {}: {}'.format(category, len(examples)))
        for node, fragments in examples[:max_examples]:
            print('    {}'.format(describe_node(node)))
            for fragment in list(fragments)[:max_examples]:
                print('      vs {}'.format(describe_node(fragment)))


def main():
    parser = argparse.ArgumentParser(
        description=
        'Compare two tileconn.json files by the nodes they reconstruct.')
    parser.add_argument('--tilegrid', required=True)
    parser.add_argument('--tileconn_a', required=True)
    parser.add_argument('--tileconn_b', required=True)
    parser.add_argument('--max_examples', type=int, default=5)
    args = parser.parse_args()

    with open(args.tilegrid) as f:
        grid = json.load(f)

    print('Expanding {} ...'.format(args.tileconn_a))
    nodes_a, wires_a = build_partition(args.tileconn_a, grid)
    print('  {} nodes over {} wires'.format(len(nodes_a), len(wires_a)))

    print('Expanding {} ...'.format(args.tileconn_b))
    nodes_b, wires_b = build_partition(args.tileconn_b, grid)
    print('  {} nodes over {} wires'.format(len(nodes_b), len(wires_b)))

    common_wires = wires_a & wires_b
    only_a_wires = wires_a - wires_b
    only_b_wires = wires_b - wires_a

    print('\nWire vocabulary:')
    print('  common: {}'.format(len(common_wires)))
    for label, only in (('A', only_a_wires), ('B', only_b_wires)):
        print('  only in {}: {}'.format(label, len(only)))
        for tile, wire in sorted(only)[:args.max_examples]:
            print('    {}/{}'.format(tile, wire))

    projected_a = project(nodes_a, common_wires)
    projected_b = project(nodes_b, common_wires)

    identical = projected_a & projected_b
    diff_a = projected_a - projected_b
    diff_b = projected_b - projected_a

    print('\nNode partitions projected onto common wires:')
    print('  identical nodes: {}'.format(len(identical)))
    print('  only in A:       {}'.format(len(diff_a)))
    print('  only in B:       {}'.format(len(diff_b)))

    if not diff_a and not diff_b:
        print('\nEQUIVALENT: both files reconstruct the same nodes on the '
              'common wire vocabulary.')
        return 0

    report_differences('A', diff_a, projected_b, args.max_examples)
    report_differences('B', diff_b, projected_a, args.max_examples)
    print('\nNOT EQUIVALENT.')
    return 1


if __name__ == '__main__':
    exit(main())
