# coding: utf-8
#
# SPDX-License-Identifier: ISC
"""Package B: assemble a top.v that instantiates one probe per tile."""

from __future__ import annotations

from typing import List

from .tile_positions import TilePos
from .tiles import TileProbeGenerator


def instance_name(idx: int) -> str:
    return "probe_%03d" % idx


def build_top_verilog(gen: TileProbeGenerator,
                      column: List[TilePos],
                      values: List[str]) -> str:
    """Generate ``top.v`` placing one probe instance per tile in ``column``.

    ``values[i]`` is the feature value for tile ``column[i]`` (gen.zero_value
    or gen.one_value).
    """
    assert len(values) == len(column)
    lines: List[str] = []
    lines.append("// Generated by bitgrid.designgen — do not edit by hand.")
    lines.append("module top();")
    pre = gen.module_preamble()
    if pre:
        lines.append(pre)
    for i, _tile in enumerate(column):
        lines.append(gen.emit_instance(instance_name(i), values[i]))
    lines.append("endmodule")
    return "\n".join(lines) + "\n"
