# coding: utf-8
#
# SPDX-License-Identifier: ISC
"""
Package B: emit a Vivado .tcl that builds a PERFRAMECRC bitstream, and an
optional runner.

The tcl is deliberately minimal and self-contained.  PERFRAMECRC is enabled so
the resulting ``.bit`` carries an explicit FAR write per frame — which is what
packages A and C rely on for unambiguous parsing.

Running Vivado requires it on PATH (or XRAY_VIVADO-style wrapper).  The runner
is a thin subprocess call; it is a stub in the sense that it is untested here
(no Vivado in this environment) but is structured for real use.
"""

from __future__ import annotations

import subprocess
from typing import Optional

TCL_TEMPLATE = """\
# Generated by bitgrid.designgen — PERFRAMECRC bitstream build.
create_project -force -part {part} design ./vivado_proj
read_verilog {{{verilog}}}
synth_design -top top
read_xdc {{{xdc}}}
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
place_design
route_design
# One explicit FAR write per frame so frame addresses are recoverable.
set_property BITSTREAM.GENERAL.PERFRAMECRC YES [current_design]
write_bitstream -force {bit}
"""


def build_tcl(part: str, verilog: str, xdc: str, bit: str) -> str:
    return TCL_TEMPLATE.format(part=part, verilog=verilog, xdc=xdc, bit=bit)


def run_vivado(tcl_path: str,
               vivado: str = "vivado",
               cwd: Optional[str] = None) -> int:
    """Invoke Vivado in batch mode on ``tcl_path``. Returns its exit code."""
    cmd = [vivado, "-mode", "batch", "-source", tcl_path]
    proc = subprocess.run(cmd, cwd=cwd)
    return proc.returncode
