# coding: utf-8
#
# SPDX-License-Identifier: ISC
"""Package B: emit XDC LOC constraints pinning each probe to its tile's site."""

from __future__ import annotations

from typing import List

from .tile_positions import TilePos
from .verilog import instance_name


def build_xdc(column: List[TilePos]) -> str:
    lines: List[str] = ["# Generated by bitgrid.designgen — probe placement"]
    for i, tile in enumerate(column):
        if not tile.site:
            raise ValueError(
                "tile %s has no usable site; pick a different site_type or "
                "provide one in the position source" % tile.name)
        cell = instance_name(i)
        lines.append(
            "set_property LOC %s [get_cells %s]" % (tile.site, cell))
    return "\n".join(lines) + "\n"


def build_index_csv(column: List[TilePos], values: List[str]) -> str:
    """Map instance -> (tile, site, value) for package C to consume."""
    out = ["index,tile,site,grid_x,grid_y,value"]
    for i, tile in enumerate(column):
        out.append(
            "%d,%s,%s,%d,%d,%s" %
            (i, tile.name, tile.site, tile.grid_x, tile.grid_y, values[i]))
    return "\n".join(out) + "\n"
